### ISSUE TITLE
why does the example usage use "170.10.0.1/16" for the docker bridge cidr?

### ISSUE THREAD

**Issue by wondersd** [Azure/terraform-azurerm-aks#122]
The default value for this according to the aks docs is "172.17.0.1/16", https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni

Can I presume the benefit is to allow for "172.17.0.1/16" to be usable in the network?

Are there downsides to not using an RFC 1918 address here?

Thanks!

**Comment by zioproto** [comment]
Since 2020 the default runtime is containerd and not Docker
https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2020-06-29

The setting docker_bridge_cidr is doing nothing. If you check the interfaces on the AKS nodes they dont have any Docker bridge configured.

The setting should be dropped from the example to avoid confusion
