### ISSUE TITLE
Missing kube_config outputs when on 1.24.x

### ISSUE THREAD

**Issue by davidkarlsen** [Azure/terraform-azurerm-aks#236]
This is really a arm <-> azurerm provider issue as described in: https://github.com/hashicorp/terraform-provider-azurerm/issues/17182 but I though I'd mention it here as a heads-up to other users, see especially the comment in: https://github.com/hashicorp/terraform-provider-azurerm/issues/17182#issuecomment-1227095235

You might want to warn users via the changelog.

```shell
│ Error: Invalid index
│ 
│   on .terraform/modules/aks.aks/outputs.tf line 60, in output "client_certificate":
│   60:   value       = azurerm_kubernetes_cluster.main.kube_config[0].client_certificate
│     ├────────────────
│     │ azurerm_kubernetes_cluster.main.kube_config has a sensitive value
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/aks.aks/outputs.tf line 66, in output "client_key":
│   66:   value       = azurerm_kubernetes_cluster.main.kube_config[0].client_key
│     ├────────────────
│     │ azurerm_kubernetes_cluster.main.kube_config has a sensitive value
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/aks.aks/outputs.tf line 72, in output "cluster_ca_certificate":
│   72:   value       = azurerm_kubernetes_cluster.main.kube_config[0].cluster_ca_certificate
│     ├────────────────
│     │ azurerm_kubernetes_cluster.main.kube_config has a sensitive value
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/aks.aks/outputs.tf line 94, in output "host":
│   94:   value       = azurerm_kubernetes_cluster.main.kube_config[0].host
│     ├────────────────
│     │ azurerm_kubernetes_cluster.main.kube_config has a sensitive value
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/aks.aks/outputs.tf line 177, in output "password":
│  177:   value       = azurerm_kubernetes_cluster.main.kube_config[0].password
│     ├────────────────
│     │ azurerm_kubernetes_cluster.main.kube_config has a sensitive value
│ 
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/aks.aks/outputs.tf line 183, in output "username":
│  183:   value       = azurerm_kubernetes_cluster.main.kube_config[0].username
│     ├────────────────
│     │ azurerm_kubernetes_cluster.main.kube_config has a sensitive value
│ 
│ The given key does not identify an element in this collection value.
```

**Comment by kkizer** [comment]
We have the same issue with the azurerm_kubernetes_cluster provider. I suspect the fix for https://github.com/hashicorp/terraform-provider-azurerm/issues/17182 does not address this. I am using the provider to create an AKS cluster. Immediately after creating the cluster I am using the Helm provider to install a helm chart and the Kubernetes provider to creat a ConfigMap.

@mbfrahry Do you need to make the same fix in the azurerm_kubernetes_cluster provider you made in the azurerm_kubernetes_cluster data source?

**Comment by zioproto** [comment]
Hello folks,
I preparing a PR to fix this issue in the terraform-azurerm-aks module.

I understand that a fix landed in the provider hashicorp/terraform-provider-azurerm version 3.20.0:
* https://github.com/hashicorp/terraform-provider-azurerm/pull/18131/
* https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#3200-august-25-2022

I tested this fix but is not complete, I still have in my terraform state:
```
"kube_config": [],
```

This is because in that patch they forgot to patch the resource in `kubernetes_cluster_resource.go`.

I understand there is a second part of the fix landing with the provider hashicorp/terraform-provider-azurerm  version 3.21.0:
* https://github.com/hashicorp/terraform-provider-azurerm/pull/18142/

At the moment I understand version 3.21.0 is still unreleased:
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#3210-unreleased

My expectation is that if version 3.21.0 correctly populates the `kube_config` in the state file, then the patch for the module is trivial, I just have to update the required provider version.

Please let me know if I missed anything.

**Comment by orelf-cw** [comment]
I'm encountering the same issue.

**Comment by zioproto** [comment]
@NissesSenap the patch to fix this problem without any change on your side is #238 and it is merged in this Terraform module but is not released into a tagged version yet.

I assume in your source code you have:

```
 module "aks" { 
    source                            = "Azure/aks/azurerm"
    version                           = "5.0.0"
......
}
```

You can use the latest version of the module pulling directly from the git repo:

```
 module "aks" { 
    source                            = "git::https://github.com/Azure/terraform-azurerm-aks.git?ref=eb3d8f1887208b499848d655f68ec652dd33498e"
    # version                           = "5.0.0"
......
}
```

This way you dont need use the `kube_config_raw` but you can continue to use `kube_config`.

**Comment by NissesSenap** [comment]
Sorry @zioproto I have mixed up all the repo tabs I have open and I didn't see that this issue was in terraform-azurerm-aks.
I thought I was in the upstream azurerm repo. 
Sorry about that.
