### ISSUE TITLE
prefix still needed when cluster_name provided

### ISSUE THREAD

**Issue by jaywithersbrewin** [Azure/terraform-azurerm-aks#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.3.9

### Module Version

6.6.0

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
module "aks" {
  source  = "Azure/aks/azurerm"
  version = "6.6.0"

  # Module doesn't allow for custom outbound Load Balancer name / option to not deploy one

  api_server_authorized_ip_ranges               = var.api_server_authorized_ip_ranges
  agents_availability_zones                     = ["1", "2"]
  agents_pool_name                              = "${module.naming_standard.azure_resources["virtual_machine_scaleset"]}-aks-c1"
  agents_max_count                              = 2 # Required when enable_auto_scaling = true
  agents_min_count                              = 1 # Required when enable_auto_scaling = true
  cluster_log_analytics_workspace_name          = "${module.naming_standard.azure_resources["log_workspace"]}-aks"
  cluster_name                                  = "${module.naming_standard.azure_resources["kubernetes_cluster"]}-c1"
  enable_auto_scaling                           = true
  identity_ids                                  = [azurerm_user_assigned_identity.c1.id]
  identity_type                                 = "UserAssigned"
  load_balancer_profile_outbound_ip_address_ids = [azurerm_public_ip.outbound_lb.id]
  local_account_disabled                        = true
  node_resource_group                           = "${module.naming_standard.azure_resources["resource_group"]}-aks-nodes" # Creates a RG dedicated to the nodes
  oidc_issuer_enabled                           = true                                                                    # Required for Azure AD authentication
  os_disk_type                                  = "Ephemeral"
  prefix                                        = "aks" # Module bug where a prefix still needs to be provided if cluster_name used
  rbac_aad_azure_rbac_enabled                   = true  # Required for Azure AD authentication with Azure RBAC
  rbac_aad_managed                              = true  # Required for Azure AD authentication
  resource_group_name                           = azurerm_resource_group.main.name
  role_based_access_control_enabled             = true # Required for Azure AD authentication
  vnet_subnet_id                                = azurerm_subnet.main.id
  #   workload_identity_enabled                     = true # Required for Azure AD authentication

  depends_on = [
    azurerm_resource_group.main # aks module fails to deploy without dependency
  ]
}
```

### tfvars variables values

```hcl
None which are relevant.
```

### Debug Output/Panic Output

```shell
Prefix must be provided.
```

### Expected Behaviour

When using the cluster_name argument, the prefix argument doesnt need to be used.

### Actual Behaviour

The prefix argument needs to be provided, even when using the cluster_name argument, even though the prefix value is then disregarded.

**Comment by zioproto** [comment]
Hello,
thanks for opening this issue.

I understand you are using `var.cluster_name` and you expect to be able to set to `null` the variable `var.prefix`.

However the variable is **required**, and it is has no default value, like you can see in the variable definition.

https://github.com/Azure/terraform-azurerm-aks/blob/3515c45be07f65acb87f2b25ada349f107eac90a/variables.tf#L1-L4

This is because the `var.prefix` is still used for the `dns_prefix`:

https://github.com/Azure/terraform-azurerm-aks/blob/3515c45be07f65acb87f2b25ada349f107eac90a/main.tf#L17-L26

And in the `name` of the log analytics workspace:

https://github.com/Azure/terraform-azurerm-aks/blob/3515c45be07f65acb87f2b25ada349f107eac90a/main.tf#L310-L319

I am not sure this is a bug, it seems rather the intended behaviour.

Could you please clarify what changes would improve your experience with the module ?

Thanks

**Comment by jaywithersbrewin** [comment]
Hello,

Thanks for the quick reply.

The dns_prefix argument for the azurerm_kubernetes_cluster resource is optional.

Instead, I think separate prefixes, would be better:

  *   cluster_prefix
  *   workspace_prefix
  *   dns_prefix

Thanks,

***@***.***

**Comment by zioproto** [comment]
Thanks for clarifying your ask. 

Do you plan to submit a PR for this change ?

**Comment by lonegunmanb** [comment]
We also must consider avoiding breaking change as there are users who're using this prefix variable now. The newly added variables could take precedence over `var.prefix`, if they're set, use these newly added variables; if not, use `var.prefix`.

Changing `var.prefix` from a required variable to an optional variable WILL NOT be considered as a breaking change, we can merge and release this feature in our next release.

I can do this pr but due to my limited bandwidth, I cannot guarantee a timeline for this. We can leave this issue open, once I have time I'll compose a pr, meanwhile, anybody is welcomed to contribute a pr for this if you're interested in it.

**Comment by jaywithersbrewin** [comment]
I’ll raise a PR for that.

Thanks 😊

***@***.***

**Comment by jaywithersbrewin** [comment]
Hi,

I don't seem to have permissions to create a remote branch.

Thanks.

***@***.***

**Comment by lonegunmanb** [comment]
Thanks @jaywithersbrewin for your contribution, please [fork this repo](https://docs.github.com/en/get-started/quickstart/fork-a-repo) and follow [Github flow](https://docs.github.com/en/get-started/quickstart/github-flow) to create a feature branch on your own forked repo, then submit your changes as a pull request to this repo's `main` branch, thanks!

**Comment by jaywithersbrewin** [comment]
Hi, checks are failing on my PR and i'm not sure how to fix. Thanks.
