### ISSUE TITLE
Support for `network_plugin_mode`

### ISSUE THREAD

**Issue by jodr5786** [Azure/terraform-azurerm-aks#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

`network_plugin_mode` was added to v3.35.0 of the azurerm provider. This option allows one to specify `Overlay`, which is currently in preview for the Azure CNI.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
From main.tf, the network_profile block, add a variable for network_plugin_mode (with a default of Overlay when the network_plugin is azure):

network_profile {
    network_plugin      = var.network_plugin
    network_plugin_mode = var.network_plugin_mode
    dns_service_ip      = var.net_profile_dns_service_ip
    docker_bridge_cidr  = var.net_profile_docker_bridge_cidr
    load_balancer_sku   = var.load_balancer_sku
    network_policy      = var.network_policy
    outbound_type       = var.net_profile_outbound_type
    pod_cidr            = var.net_profile_pod_cidr
    service_cidr        = var.net_profile_service_cidr

  }
```

**Comment by zioproto** [comment]
hello @jodr5786 

the issue is that until the feature is in Preview it is also needed to register the preview flag for the feature to work:
https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#register-the-azureoverlaypreview-feature-flag

and with the module we would have to check we are deploying with Terraform in a region where the feature in preview is supported.

Also you have this limit that ["You can't use Application Gateway as an Ingress Controller (AGIC) for an overlay cluster"](https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#limitations-with-azure-cni-overlay), then we would also have to implement logic to prevent `ingress_application_gateway_enabled` to be enabled at the same time.

I suggest to hold until the feature is GA before implementing it in the module, because some limitations might go away.

**Comment by bmnolan** [comment]
Hi @zioproto 
  This feature looks like it went GA on April 17th
  https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-azure-cni-overlay-in-azure-kubernetes-service
