### ISSUE TITLE
Support for image_cleaner & image_cleaner_interval_hours

### ISSUE THREAD

**Issue by aevlogiev** [Azure/terraform-azurerm-aks#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

image_cleaner_enabled - (Optional) Specifies whether Image Cleaner is enabled.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#image_cleaner_enabled

image_cleaner_interval_hours - (Optional) Specifies the interval in hours when images should be cleaned up. Defaults to 48
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#image_cleaner_interval_hours

This feature helps clean the unused images, although it can be updated manually on a cluster level, doing it manually triggers terraform change, along with the missing lifecycle option, we need to enable it each time we run terraform

This requires that the Preview Feature Microsoft.ContainerService/EnableImageCleanerPreview is enabled and the Resource Provider is re-registered, see [the documentation](https://learn.microsoft.com/en-us/azure/aks/image-cleaner) for more information.

### New or Affected Resource(s)/Data Source(s)

module.aks.azurerm_kubernetes_cluster.main

### Potential Terraform Configuration

```hcl
module "aks" {
  source  = "Azure/aks/azurerm"
  version = "6.7.1"
  image_cleaner_enabled = true/false (defaults to false)
  image_cleaner_interval_hours = 48
}
```

**Comment by zioproto** [comment]
@aevlogiev I would propose we implement this as soon as the feature is GA.
The shift from Public Preview to GA is tracked here: https://github.com/Azure/AKS/issues/2912

Would this work for you ?

**Comment by lonegunmanb** [comment]
> @aevlogiev I would propose we implement this as soon as the feature is GA. The shift from Public Preview to GA is tracked here: [Azure/AKS#2912](https://github.com/Azure/AKS/issues/2912)
> 
> Would this work for you ?

Agreed, I'd like to support this feature when it's not preview.

**Comment by aevlogiev** [comment]
Perfect @zioproto @lonegunmanb thanks

**Comment by lonegunmanb** [comment]
Hi @skolobov sorry for the late reply and thanks for your pr, unfortunately I agree with @zioproto, since the feature is still in preview, I'd like to wait for its GA.

A preview feature's API might be changed significantly, or even been revoked. We can only introduce breaking change to this module only when we'd like to publish a major version upgrade, and we take these kinds of breaking changes very seriously. So, I'd like to wait for GA, please accept my apology. When the feature is GA would you please update your pr and ping me to kick off the e2e test? Thanks for your contribution and understanding!

**Comment by amoosbr** [comment]
The [AKS image cleaner feature is now GA](https://azure.microsoft.com/en-us/updates/ga-aks-image-cleaner/).
Perhaps the merge conflict of the [existing PR](https://github.com/Azure/terraform-azurerm-aks/pull/343) can be solved and the PR merged.
