### ISSUE TITLE
api_server_authorized_ip_ranges needs to be set to "0.0.0.0/32" with public access enabled. "0.0.0.0/32" is only "0.0.0.0"

### ISSUE THREAD

**Issue by bkolve** [Azure/terraform-azurerm-aks#370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.3.9

### Module Version

7.0.0

### AzureRM Provider Version

3.5.7

### Affected Resource(s)/Data Source(s)

azurem_kubernetes_cluster

### Terraform Configuration Files

```hcl
module "aks" {

...

public_network_access_enabled         = true
api_server_authorized_ip_ranges       = ["0.0.0.0/32"]
}
```

### tfvars variables values

```hcl
.
```

### Debug Output/Panic Output

```shell
Error: Resource precondition failed
│ 
│   on .terraform/modules/aks/main.tf line 446, in resource "azurerm_kubernetes_cluster" "main":
│  446:       condition     = !var.public_network_access_enabled || try(contains(var.api_server_authorized_ip_ranges, "0.0.0.0/32"), false)
│     ├────────────────
│     │ var.api_server_authorized_ip_ranges is set of string with 1 element
│     │ var.public_network_access_enabled is true
│ 
│ When `public_network_access_enabled` is set to true, `0.0.0.0/32` must be
│ added to `authorized_ip_ranges` in the `api_server_access_profile block`
│ (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#public_network_access_enabled).

```

### Expected Behaviour

when public api access is enabled, I'd expect netmask needing to be anything but 0.0.0.0/32 (effectively blocking all addresses).

Or am I missing something here? 
Thanks in advance!

### Actual Behaviour

I'm forced to set 0.0.0.0/32, thus blocking all api server access.

**Comment by zioproto** [comment]
Hello,

this was introduced in https://github.com/Azure/terraform-azurerm-aks/pull/361

What is implemented comes from the provider documentation:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#public_network_access_enabled

![Screenshot 2023-05-20 at 17 35 18](https://github.com/Azure/terraform-azurerm-aks/assets/789701/f05de5c4-bfb5-4697-a20f-041010af4874)

This originally comes from this commit:
https://github.com/hashicorp/terraform-provider-azurerm/commit/afd18e49d63d4d0b3a9e573fe93686fc083a66cd

@ms-henglu please have a look. I think this note is confusing.

If we look at the Azure CLI options `--api-server-authorized-ip-ranges`
https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create

![Screenshot 2023-05-20 at 18 08 52](https://github.com/Azure/terraform-azurerm-aks/assets/789701/6c48cbae-5009-48d3-9d77-3e0b973dce88)

It says to use the range 0.0.0.0/32 to restrict apiserver traffic to node pools, because it blocks basically everything.

Setting `api_server_authorized_ip_ranges` with `["0.0.0.0/32"]` in the list prevents any other connection to the API server, even if other ranges are added to the list, so this cannot be a pre-condition.

Actually other ranges are not event allowed at that point, If you attempt to do this with the Azure Portal you even see this problem:
![Screenshot 2023-05-20 at 18 17 13](https://github.com/Azure/terraform-azurerm-aks/assets/789701/703c8ab4-c732-408e-9cad-9ed7c27998c5)

@lonegunmanb should we revert https://github.com/Azure/terraform-azurerm-aks/pull/361 ?

**Comment by lonegunmanb** [comment]
I'm studying the [commit](https://github.com/hashicorp/terraform-provider-azurerm/commit/afd18e49d63d4d0b3a9e573fe93686fc083a66cd) that introduced this restriction into the document, it seems like the document is wrong. I'll do some tests to verify it.

**Comment by lonegunmanb** [comment]
I've verified that `api_server_authorized_ip_ranges` **won't** be affected by `public_access_enabled` anymore. We should revert #361 to solve this issue.
