### ISSUE TITLE
State drift due to upgrade_settings -> max_surge

### ISSUE THREAD

**Issue by Israphel** [Azure/terraform-azurerm-aks#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

brownfield

### Terraform Version

1.5.5

### Module Version

8.0.0

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
All defaults.
```

### tfvars variables values

```hcl
Kubernetes version set to 1.28.x
```

### Debug Output/Panic Output

```shell
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.aks-us-east["use-1"].azurerm_kubernetes_cluster.main will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "main" {
        id                                  = "/subscriptions/xxx/resourceGroups/prod-us-east/providers/Microsoft.ContainerService/managedClusters/use-prod-1-aks"
        name                                = "use-prod-1-aks"
        tags                                = {
            "environment" = "prod"
            "managed_by"  = "terraform"
            "region"      = "eastus"
        }
        # (31 unchanged attributes hidden)

      ~ default_node_pool {
            name                         = "default"
            tags                         = {
                "environment" = "prod"
                "managed_by"  = "terraform"
                "region"      = "eastus"
            }
            # (25 unchanged attributes hidden)

          - upgrade_settings {
              - max_surge = "10%" -> null
            }
        }

        # (6 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

We're not setting up any setting for max_surge, it should respect default (10%)

### Actual Behaviour

Every plan wants to remove the block again.

### Steps to Reproduce

terraform plan

### References

Related to: https://github.com/hashicorp/terraform-provider-azurerm/issues/24020

**Comment by lonegunmanb** [comment]
@Israphel thanks for reporting this issue to us. As [Aks release log](https://github.com/Azure/AKS/releases/tag/2023-10-01) shows:

* The default [max surge](https://learn.microsoft.com/azure/aks/upgrade-cluster?tabs=azure-cli#customize-node-surge-upgrade) value during upgrades will be changed from 1 to 10% for AKS 1.28+ on new clusters to improve upgrade latency.

This is an expected behavior if you've set `kubernetes_version` to `1.28+`. I can reproduce this issue by the following code:

```hcl
resource "random_id" "prefix" {
  byte_length = 8
}

resource "random_id" "name" {
  byte_length = 8
}

resource "azurerm_resource_group" "main" {
  location = "eastus"
  name     = "${random_id.prefix.hex}-rg"
}

module "aks" {
  source = "../.."

  kubernetes_version = "1.29.0"
  prefix              = random_id.prefix.hex
  resource_group_name = azurerm_resource_group.main.name
  rbac_aad            = false
}
```

This is not this module's issue, the root cause is by the service team's design. You can bypass this drift by setting `max_surge` to `"10%"` explicitly. I'd like to keep this issue open and add a `check` block to provide a warning to users, but we can do nothing to eliminate this configuration drift I think.

**Comment by lonegunmanb** [comment]
@Israphel 

>is it with https://github.com/Azure/terraform-azurerm-aks?tab=readme-ov-file#input_agents_pool_max_surge ?

Correct!
