### ISSUE TITLE
Support for Application Gateway for Containers

### ISSUE THREAD

**Issue by paweloczadly** [Azure/terraform-azurerm-aks#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Are there any plans to support [Azure Application Gateway for Containers](https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/) in this project?

### New or Affected Resource(s)/Data Source(s)

* azurerm_application_load_balancer
* azurerm_resource_provider_registration

### References

https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/

**Comment by zioproto** [comment]
hello @paweloczadly 

Application Gateway for Containers is now GA:
https://azure.microsoft.com/en-gb/updates/general-availability-application-gateway-for-containers/

The ALB controller is installed as an helm chart, there is no way to install it directly as an AKS add-on (this was the case for the previous Application Gateway).

This means we would have to add the helm Terraform provider to this module. See example:
https://github.com/zioproto/istio-aks-example/blob/b84bf181daa6dbc5c78518137ff88fb497aa8525/istio-on-aks/istio-tf/alb.tf#L10-L27

There are also azure identities required, I have an example here:
https://github.com/zioproto/istio-aks-example/blob/b84bf181daa6dbc5c78518137ff88fb497aa8525/istio-on-aks/aks-tf/identity.tf#L1-L37

Because this is not just an AKS add-on feature to toggle on/off I am not sure if this "Application Gateway for Containers" product requires an additional dedicated module.

Cc: @lonegunmanb @matt-FFFFFF for Terraform comments.

Cc: @JackStromberg to confirm that installing the helm chart is the long term way to install the ALB controller on AKS.

**Comment by paweloczadly** [comment]
Hi @zioproto,

Thank you for your response and the broader context. Do you see any challenges that suggest integrating the Helm provider and Azure identities might be problematic? I can understand that Application Gateway for Containers is not an AKS add-on, but it is mentioned in the official Azure documentation:

> "Application Gateway for Containers is the evolution of the [Application Gateway Ingress Controller](https://learn.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview) (AGIC), a [Kubernetes](https://learn.microsoft.com/en-us/azure/aks) application that enables Azure Kubernetes Service (AKS) customers to use Azure's native Application Gateway application load-balancer."[^1]

Considering this, I think it might be useful to have this feature in the terraform-azurerm-aks module.

[^1]: [What is Application Gateway for Containers?](https://learn.microsoft.com/en-us/azure/application-gateway/for-containers/overview)

**Comment by zioproto** [comment]
@paweloczadly the problem integrating the Helm provider in this module is the following:

https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources

This is valid for the Kubernetes provider but also for any other provider that needs to consume the Kubernetes API of a cluster created in the same `terraform apply` operation.

**Comment by lonegunmanb** [comment]
I'm closing this issue @paweloczadly and I don't think adding more features into this module is a good idea. Please feel free to reopen it if you have different thought.
