### ISSUE TITLE
AKS node pool Autoscaling not working properly

### ISSUE THREAD

**Issue by Sagarsinghinfra360** [Azure/terraform-azurerm-aks#612]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.30.4

### Module Version

8.0.0

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

autoscalling

### Terraform Configuration Files

```hcl
enable_auto_scaling                     = "true"
```

### tfvars variables values

```hcl
-
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

Describe the bug
Default autoscaling profile for node pool not scaling down nodes properly.

I have a v1.30.4 AKS cluster with a single node pool that's configured for autoscaling with default profile. Min is set to 2 and max is set to 10 for number of nodes. Currently 6 nodes are running.

The CPU utilization for each node is equal or less than 11%. Memory utilization for each node is: 60%, 58%, 48%, 41%, 33%, 28%.

Expected behavior
The default scale-down utilization is 50%. So node3, node4, node5 and node6 should have been scaled down and the cluster should have 2 or 3 nodes running instead of 6.

**Comment by zioproto** [comment]
Hello,

1. This is not a Terraform problem. You should rather report this issue at https://github.com/Azure/AKS or open a ticket with Microsoft Azure support.

2. The actual node CPU and memory utilization might be irrelevant. When you create Pods you indicate in the pod spec a request for CPU and memory. The kubernetes scheduler uses this information to place Pods on Nodes. The autoscaler creates extra nodes eventually if the cluster does not meet the **requested** capacity. Your cluster might now scale down because you requested capacity, even if you are not using it. Are you setting correctly requests and limits for your Pods ? https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-requests-and-limits-of-pod-and-container
